{
 "title": "GIM dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "GIM servers status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gim_server_state",
     "legendFormat": "{{pod}}   =  {{schema_version}}"
    }
   ]
  },
  {
   "title": "Number of Failed Kafka  Transform",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gim_number_failed_kafkajob" }
   ]
  },
  {
   "title": "Number of  Failed Transform Jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gim_failed_jobsteps", "legendFormat": "{{pod}} {{failedJobSteps}}" }
   ]
  },
  {
   "title": "Kafka Letancy per topic and partition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gim_kafka_timestamp_behind/60000",
     "legendFormat": "{{pod}}  partition: {{partition}}  {{topic}}"
    }
   ]
  }
 ]
}