{
 "title": "Genesys Authentication Service Health ",
 "tags": [
  "gauth",
  ""
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "prometheus" },
   { "name": "svcAuth", "query": "gauth-auth" }
  ]
 },
 "panels": [
  {
   "title": "Auth Service API requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by(container)(rate(api_requests_seconds_count_total{namespace=\"gauth\", job=\"$svcAuth\"}[5m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Auth Service API requests per instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(api_requests_seconds_count_total{namespace=\"gauth\", job=\"$svcAuth\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Auth Service 4xx responses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(container)(rate(jetty_responses_total{status=\"4xx\",namespace=\"gauth\", job=\"$svcAuth\"}[5m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Auth Service 4xx responses per instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(jetty_responses_total{status=\"4xx\",namespace=\"gauth\", job=\"$svcAuth\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Auth Service 5xx responses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(container)(rate(jetty_responses_total{status=\"5xx\",namespace=\"gauth\", job=\"$svcAuth\"}[5m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Auth Service 5xx responses per instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(jetty_responses_total{status=\"5xx\",namespace=\"gauth\", job=\"$svcAuth\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Auth Service requests latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(container)(rate(api_requests_seconds_sum_total{namespace=\"gauth\", job=\"$svcAuth\"}[5m])) / sum by(consul_service)(rate(api_requests_seconds_count_total{namespace=\"gauth\", job=\"$svcAuth\"}[5m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Auth Service requests latency per instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(api_requests_seconds_sum_total{namespace=\"gauth\", job=\"$svcAuth\"}[5m]) / rate(api_requests_seconds_count_total{namespace=\"gauth\", job=\"$svcAuth\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Config Server command timeouts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (environment) (rate(auth_cs_command_timeouts_total{namespace=\"gauth\", job=\"$svcAuth\"}[5m]))",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Config Server connection timeouts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (environment) (rate(auth_cs_connection_timeouts_total{namespace=\"gauth\", job=\"$svcAuth\"}[5m]))",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Redis cluster free memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "azure_RedisCache_usedmemorypercentage {resource_group=~\".*-gauth-.*\"}",
     "legendFormat": "{{consul_service}}"
    }
   ]
  },
  {
   "title": "Redis DB keys",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "azure_RedisCache_totalkeys {resource_group=~\".*-gauth-.*\"}",
     "legendFormat": "{{consul_service}}"
    }
   ]
  }
 ]
}