{
 "title": "GES - Performance",
 "description": "A dashboard for monitoring the performance of GES in an Azure Deploymen",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Pod", "query": "label_values(pod)" },
   {
    "name": "Tenant",
    "query": "label_values(ges_callbacks_created, tenant)"
   }
  ]
 },
 "panels": [
  {
   "title": "Health and Liveliness",
   "type": "flant-statusmap-panel",
   "description": "Detailed health of GES and the services it relies upon.",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(GES_HEALTH{pod=~\"$Pod\"}) or 1",
     "legendFormat": "GES"
    },
    {
     "expr": "avg(GWS_CONFIG_STATUS{pod=~\"$Pod\"})",
     "legendFormat": "GWS CONFIG"
    },
    {
     "expr": "avg(GWS_ENV_STATUS{pod=~\"$Pod\"})",
     "legendFormat": "GWS ENV"
    },
    {
     "expr": "avg(GWS_AUTH_STATUS{pod=~\"$Pod\"})",
     "legendFormat": "GWS AUTH"
    },
    {
     "expr": "avg(ALL_ORS_DOWN{pod=~\"$Pod\"}) or 0",
     "legendFormat": "ORS"
    },
    {
     "expr": "avg(ALL_URS_DOWN{pod=~\"$Pod\"}) or 0",
     "legendFormat": "URS"
    },
    {
     "expr": "avg(REDIS_CONNECTION{pod=~\"Pod\"})",
     "legendFormat": "REDIS"
    },
    {
     "expr": "avg(ORS_REDIS_STATUS{pod=~\"$Pod\"})",
     "legendFormat": "ORS REDIS"
    }
   ]
  },
  { "title": "System Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "time() - ges_process_start_time_seconds{pod=~\"$Pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (irate(ges_process_cpu_seconds_total{pod=~\"$Pod\"}[1m]))",
     "legendFormat": "CPU Usage - {{pod}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ges_nodejs_eventloop_lag_seconds{pod=~\"$Pod\"}",
     "legendFormat": "Event Loop Lag - ({{pod}})"
    }
   ]
  },
  {
   "title": "Memory Use (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit", "label": "Memory in Use (%)" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{pod=~\"$Pod\"}) / sum by (pod) (kube_pod_container_resource_limits_memory_bytes{pod=~\"$Pod\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "Memory Usage" }
   ],
   "targets": [
    {
     "expr": "ges_process_resident_memory_bytes{pod=~\"$Pod\"}",
     "legendFormat": " {{pod}}"
    }
   ]
  },
  {
   "title": "Terminating Pods",
   "type": "table",
   "description": "A table listing pods in the terminating state. If a pod persists on this list, it might be indicative of some deeper routed issues with the deployment",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 25 },
   "targets": [
    {
     "expr": "count(kube_pod_deletion_timestamp{namespace=\"ges\"}) by (namespace, pod) * count(kube_pod_status_reason{reason=\"PodLost\", namepace=\"ges\"} == 0) by (namespace, pod)"
    }
   ]
  },
  { "title": "Kube Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Active GES Kube Pods",
   "type": "graph",
   "description": "The number of active pods for Conversation Provider in the Deployment",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"ges-prod.*\", phase=~\"Running\"})",
     "legendFormat": "Pods Running"
    }
   ]
  },
  { "title": "API Performance (General)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "API Calls / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "calls / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ges_http_request_duration_seconds_count{pod=~\"$Pod\"}[5m]) * 60) ",
     "legendFormat": "All Requests"
    },
    {
     "expr": "sum(rate(ges_http_request_duration_seconds_count{code=~\"(200|302)\", pod=~\"$Pod\"}[5m]) * 60) ",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(ges_http_request_duration_seconds_count{code!~\"(200|302)\", pod=~\"$Pod\"}[5m]) * 60)",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Avg. Response Time (By Pod}}",
   "type": "graph",
   "description": "The average response time of GES to incoming API requests across all API Endpoints. A 15 minute moving average",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s", "label": "Response Time (s)" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(increase(ges_http_request_duration_seconds_sum{pod=~\"$Pod\"}[15m])) / sum by (pod)(increase(ges_http_request_duration_seconds_count{pod=~\"$Pod\"}[15m]))",
     "legendFormat": "All Routes -- {{pod}}"
    }
   ]
  },
  {
   "title": "HTTP 400 Errors  / Min",
   "type": "graph",
   "description": "HTTP 400 Errors over time on the selected GES pod ",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "Errors / Min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ges_http_failed_requests_total{httpCode=\"400\", pod=~\"$Pod\", tenant=~\"$Tenant\"}[5m]) * 60)",
     "legendFormat": "All Selected Tenants"
    },
    {
     "expr": "sum by (tenant) (rate(ges_http_failed_requests_total{httpCode=\"400\", pod=~\"$Pod\", tenant=~\"$Tenant\"}[5m]) * 60)",
     "legendFormat": "{{Exported Tenant}}"
    }
   ]
  },
  {
   "title": "Avg. Response Time (By Endpoint)",
   "type": "graph",
   "description": "The average response time of GES to incoming API requests across all API Endpoints. A 15 minute moving average",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s", "label": "Response Time (s)" }
   ],
   "targets": [
    {
     "expr": "sum by (method, route, code)(increase(ges_http_request_duration_seconds_sum{pod=~\"$Pod\"}[15m])) / sum by (method, route, code)(increase(ges_http_request_duration_seconds_count{pod=~\"$Pod\"}[15m]))",
     "legendFormat": "{{method}} / {{code}} - {{route}}"
    }
   ]
  },
  {
   "title": "HTTP 500 Errors / Hr",
   "type": "graph",
   "description": "HTTP 500 Errors over time on the selected GES pod & tenant",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Errors / Hr" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ges_http_failed_requests_total{httpCode=\"401\", pod=~\"$Pod\", tenant=~\"($Tenant|undefined)\"}[5m]) * 60)",
     "legendFormat": "All Selected Tenants"
    },
    {
     "expr": "sum by (tenant) (rate(ges_http_failed_requests_total{httpCode=\"401\", pod=~\"$Pod\", tenant=~\"($Tenant|undefined)\"}[5m]) * 60)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "HTTP 401 Errors / min",
   "type": "graph",
   "description": "HTTP 401 Errors over time on the selected GES pod & tenant",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "Errors / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ges_http_failed_requests_total{httpCode=\"401\", pod=~\"$Pod\"}[5m]) * 60)"
    }
   ]
  },
  {
   "title": "HTTP 404 Errors / Min",
   "type": "graph",
   "description": "HTTP 404 Errors over time on the selected GES pod. Due to how requests resulting in a 404 are handled they are not able to be tracked on a per-tenant basis.",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "Errors / Min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ges_http_failed_requests_total{httpCode=\"500\", pod=~\"$Pod\", tenant=~\"($Tenant|undefined)\"}[5m]) * 60)",
     "legendFormat": "HTTP 500 Errors / Min"
    },
    {
     "expr": "sum by (tenant) (rate(ges_http_failed_requests_total{httpCode=\"500\", pod=~\"$Pod\", tenant=~\"($Tenant|undefined)\"}[5m]) * 60)",
     "legendFormat": "{{tenant}}"
    }
   ]
  }
 ]
}