{
 "title": "UCS-X RDS Performance",
 "description": "Monitoring of activity of SQL operations",
 "tags": [ "__ucsx__" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   { "name": "ActiveTenantName", "label": "Tenant", "query": "ucsx_sql_count" }
  ]
 },
 "panels": [
  { "title": "DB state and SQL performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Size of DB pool connections (per contact center)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ucsx_dbPool{metric=\"total\", ccName=~\"$ActiveTenantName\"}",
     "legendFormat": "{{ ccName }}"
    }
   ]
  },
  {
   "title": "DB Request Rate total, rps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ccName, job) (rate(ucsx_sql_count{ccName=~\"$ActiveTenantName\"}[1m]))",
     "legendFormat": "{{ ccName }}"
    }
   ]
  },
  {
   "title": "DB Request Rate, rps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation, job) (rate(ucsx_sql_count{ccName=~\"$ActiveTenantName\", operation!=\"read\", operation!=\"write\", operation!=\"rawSql\"}[1m]))",
     "legendFormat": "{{ operation  }}"
    }
   ]
  },
  {
   "title": "Average DB Request processing time, ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (ccName, job) (rate(ucsx_sql_sum{ccName=~\"$ActiveTenantName\"}[1m])))/(sum by (ccName, job) (rate(ucsx_sql_count{ccName=~\"$ActiveTenantName\"}[1m])))",
     "legendFormat": "{{ ccName }}"
    }
   ]
  },
  {
   "title": "Average DB Request processing time by operations, ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(ucsx_sql_sum{ccName=~\"$ActiveTenantName\", operation!=\"read\", operation!=\"write\"}[1m]))/sum by (operation) (rate(ucsx_sql_count{ccName=~\"$ActiveTenantName\", operation!=\"read\", operation!=\"write\"}[1m]))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  { "title": "DB Request Rate Quantiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Select Request process time quantiles, ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ucsx_sql_bucket{ccName=~\"$ActiveTenantName\", operation=\"query\"}[1m])",
     "legendFormat": "< {{ le }} ms"
    }
   ]
  },
  {
   "title": "Insert Request process time quantiles, ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ucsx_sql_bucket{ccName=~\"$ActiveTenantName\", operation=\"insert\"}[1m])",
     "legendFormat": "< {{ le }} ms"
    }
   ]
  },
  {
   "title": "Update Request process time quantiles, ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ucsx_sql_bucket{ccName=~\"$ActiveTenantName\", operation=\"update\"}[1m])",
     "legendFormat": "< {{ le }} ms"
    }
   ]
  },
  {
   "title": "Delete Request process time quantiles, ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ucsx_sql_bucket{ccName=~\"$ActiveTenantName\", operation=\"delete\"}[1m])",
     "legendFormat": "< {{ le }} ms"
    }
   ]
  },
  {
   "title": "Direct DB Request process time quantiles, ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ucsx_sql_bucket{ccName=~\"$ActiveTenantName\", operation=\"rawSql\"}[1m])",
     "legendFormat": "< {{ le }} ms"
    }
   ]
  },
  { "title": "UCS-X dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  { "type": "dashlist", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 59 } }
 ]
}