{
 "title": "UCS-X QoS",
 "tags": [ "__ucsx__" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "ActiveTenantName",
    "label": "Name of active tenant to be detailed",
    "query": "ucsx_http_request_duration_count{url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}"
   },
   { "name": "MethodName", "query": "GET, PUT, POST, DELETE" },
   {
    "name": "RequestUrl",
    "label": "Request URL to be detailed",
    "query": "ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}"
   }
  ]
 },
 "panels": [
  { "title": "HTTP request rate, rps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP request rate by Pod instance, rps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance, job) (rate(ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\", url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\"}[1m]))",
     "legendFormat": "{{ pod }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "HTTP request rate by tenant, rps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ccName, job) (rate(ucsx_http_request_duration_count{url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\", ccName=~\"$ActiveTenantName\"}[1m]))",
     "legendFormat": "{{ ccName }}"
    }
   ]
  },
  {
   "title": "Config API and Metrics request rate, rps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(ucsx_http_request_duration_count{url=\"/metrics\"}[1m]))",
     "legendFormat": "Metrics"
    },
    {
     "expr": "sum by (job) (rate(ucsx_http_request_duration_count{url=~\"(/ucs/v3/config/healthcheck|/ucs/v3/healthcheck)\"}[1m]))",
     "legendFormat": "Healthcheck"
    },
    {
     "expr": "sum by (job) (rate(ucsx_http_request_duration_count{url=~\"/ucs/v3/config.*\", url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\"}[1m]))",
     "legendFormat": "Config API"
    }
   ]
  },
  { "title": "HTTP request processing time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "HTTP request processing average time per Pod instance, ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, instance, job) (rate(ucsx_http_request_duration_sum{url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/ucs/v3/notifications/connect\", ccName=~\"$ActiveTenantName\"}[1m]))/sum by (pod, instance, job)(rate(ucsx_http_request_duration_count{url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/ucs/v3/notifications/connect\", ccName=~\"$ActiveTenantName\"}[1m]))",
     "legendFormat": "{{ pod }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "HTTP request average processing time per tenant, ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ccName, job) (rate(ucsx_http_request_duration_sum{url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/ucs/v3/notifications/connect\", ccName=~\"$ActiveTenantName\",}[1m]))/sum by (ccName, job) (rate(ucsx_http_request_duration_count{url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/ucs/v3/notifications/connect\", ccName=~\"$ActiveTenantName\"}[1m]))",
     "legendFormat": "{{ ccName }}"
    }
   ]
  },
  {
   "title": "Config API and Metrics request average processing , ms",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(ucsx_http_request_duration_sum{url=\"/metrics\"}[1m]))/sum by (job) (rate(ucsx_http_request_duration_count{url=\"/metrics\"}[1m]))",
     "legendFormat": "Metrics"
    },
    {
     "expr": "sum by (job) (rate(ucsx_http_request_duration_sum{url=~\"(/ucs/v3/config/healthcheck|/ucs/v3/healthcheck)\"}[1m]))/sum by (job) (rate(ucsx_http_request_duration_count{url=~\"(/ucs/v3/config/healthcheck|/ucs/v3/healthcheck)\"}[1m]))",
     "legendFormat": "Healthcheck"
    },
    {
     "expr": "sum by (job) (rate(ucsx_http_request_duration_sum{url=~\"/ucs/v3/config.*\", url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\"}[1m]))/sum by (job) (rate(ucsx_http_request_duration_count{url=\"/metrics\"}[1m]))",
     "legendFormat": "Config Api"
    }
   ]
  },
  { "title": "HTTP requests timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Histogram of HTTP request processing time, rps",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (le, job) (rate(ucsx_http_request_duration_bucket{url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m]))",
     "legendFormat": "< {{ le }}"
    }
   ]
  },
  {
   "title": "Histogram of HTTP request processing of specific tenant: '$ActiveTenantName', rps",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (rate(ucsx_http_request_duration_bucket{ccName=~\"$ActiveTenantName\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m]))",
     "legendFormat": "< {{ le }}"
    }
   ]
  },
  { "title": "HTTP Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Error responses, responses/second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate (ucsx_http_request_duration_count{code=~\"4.*\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum by (job) (rate (ucsx_http_request_duration_count{code=~\"5.*\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum by (job) (rate (ucsx_overload_protection_count[1m]))",
     "legendFormat": "503"
    }
   ]
  },
  {
   "title": "Error responses per tenant: '$ActiveTenantName', responses/second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\",code=~\"4.*\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate (ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\",code=~\"5.*\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Error responses, %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum by (job) (rate (ucsx_http_request_duration_count{code=~\"4.*\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m]))/(1e-30+sum by (job) (rate (ucsx_http_request_duration_count{url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m])))",
     "legendFormat": "4xx"
    },
    {
     "expr": "100 * sum by (job) (rate (ucsx_http_request_duration_count{code=~\"5.*\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m]))/(1e-30+sum by (job) (rate (ucsx_http_request_duration_count{url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m])))",
     "legendFormat": "5xx"
    },
    {
     "expr": "100 * (sum by (job) (rate (ucsx_overload_protection_count[1m])))/(sum by (job) (rate (ucsx_http_request_duration_count{url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m])))",
     "legendFormat": "503"
    }
   ]
  },
  {
   "title": "Error responses per tenant: '$ActiveTenantName', %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100* sum(rate (ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\",code=~\"4.*\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m]))/(1e-10+sum(rate (ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\", code=~\"4.*\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m])))",
     "legendFormat": "4xx"
    },
    {
     "expr": "100*sum(rate (ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\",code=~\"5.*\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m]))/(1e-10+sum(rate (ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\", code=~\"5.*\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/ucs/v3/healthcheck\",url!=\"/favicon.ico\"}[1m])))",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "HTTP requests details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "HTTP requests activity per tenant: '$ActiveTenantName', rps",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (url, method) (rate(ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/favicon.ico\"}[1m]))",
     "legendFormat": "{{ method }}: {{ url }}"
    }
   ]
  },
  {
   "title": "HTTP requests processing time per tenant: '$ActiveTenantName', ms",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (url, method) (rate(ucsx_http_request_duration_sum{ccName=~\"$ActiveTenantName\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/favicon.ico\"}[1m])/rate(ucsx_http_request_duration_count{ccName=~\"$ActiveTenantName\",url!=\"/metrics\",url!=\"/ucs/v3/config/healthcheck\",url!=\"/favicon.ico\"}[1m]))"
    }
   ]
  },
  { "title": "HTTP request QoS timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "HTTP $MethodName request '$RequestUrl' activity per tenant: '$ActiveTenantName', rps",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (rate(ucsx_http_request_duration_bucket{ccName=~\"$ActiveTenantName\",url=\"$RequestUrl\",method=\"$MethodName\"}[1m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "UCS-X dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  { "title": "List of related dashboards", "type": "dashlist", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 110 } }
 ]
}